services:

  api:
    build:
      context: .
      dockerfile: deploy/Dockerfile
      args:
        SERVICE: api
    env_file: .env
    environment:
      API_ADDR: ":8080"
    ports:
      - "8080:8080"

  gt06-listener:
    build:
      context: .
      dockerfile: deploy/Dockerfile
      args:
        SERVICE: gt06-listener
    env_file: .env
    environment:
      GT06_TCP_ADDR: ":9001"
    ports:
      - "9001:9001"

  uniguard-listener:
    build:
      context: .
      dockerfile: deploy/Dockerfile
      args:
        SERVICE: uniguard-listener
    env_file: .env
    environment:
      UNIGUARD_TCP_ADDR: ":9002"
    ports:
      - "9002:9002"

  teltonika-listener:
    build:
      context: .
      dockerfile: deploy/Dockerfile
      args:
        SERVICE: teltonika-listener
    env_file: .env
    environment:
      TELTONIKA_TCP_ADDR: ":9003"
    ports:
      - "9003:9003"